### ISSUE TITLE
Script not working since upgrade to HA 2021.12.0

### ISSUE THREAD

**Issue by frittes** [lubeda/awtrix_python_script#1]
The script raises an error:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:170 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 12:18:41 (2 occurrences) 
Last logged: 12:19:01

[140068803523200] The system cannot restart because the configuration is not valid: Platform error notify.awtrix - cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/opt/homeassistant/lib/python3.9/site-packages/homeassistant/const.py)
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 733, in admin_handler
    await result
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/homeassistant/__init__.py", line 170, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error notify.awtrix - cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/opt/homeassistant/lib/python3.9/site-packages/homeassistant/const.py)

**Comment by frittes** [comment]
Sorry, my fault. To custom_component does not work with 2021.12.0, the python_script works.
